### ISSUE TITLE
是否应该按照不同类来分别放置方法

### ISSUE THREAD

**Issue by miixcc** [linyuansup/Synthesizer-V-Script-Helper#1]
如getDuration()这个方法，在四个类中分别出现，而他们的描述却是不同的。

**Comment by linyuansup** [comment]
hhh好像真的是哎
我也只是把官方文档给翻译了下就拷进来了（x）

**Comment by linyuansup** [comment]
hhhh好像是的哎
其实就是把sv的官方文档翻译了下就拷下来了（

**Comment by linyuansup** [comment]
刚刚看了下发下官方文档好像没标注属于哪个类
我好晕_(:з」∠)_

**Comment by miixcc** [comment]
左侧的Classes展开就是了啊（？
